apiVersion: v1
kind: Deployment
metadata:
   labels:
     app: frontend
   name: frontend
   namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  tempalte:
    containers:
      - name: frontend
        image: 
        imagePullPolicy: IfNotPresent    
        resources:
          requests:
            cpu: "1.0"
            memory: "1G"
          limits:
            cpu: "1.0"
            memory: "1G"